//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuurency_Service.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ibaspro.com.org/", ConfigurationName="ServiceReference1.clsDataAccessServicesSoap")]
    public interface clsDataAccessServicesSoap {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface clsDataAccessServicesSoapChannel : Cuurency_Service.ServiceReference1.clsDataAccessServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class clsDataAccessServicesSoapClient : System.ServiceModel.ClientBase<Cuurency_Service.ServiceReference1.clsDataAccessServicesSoap>, Cuurency_Service.ServiceReference1.clsDataAccessServicesSoap {
        
        public clsDataAccessServicesSoapClient() {
        }
        
        public clsDataAccessServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public clsDataAccessServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clsDataAccessServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clsDataAccessServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ibaspro.com.org/", ConfigurationName="ServiceReference1.clsDataAccessServicesSoap12")]
    public interface clsDataAccessServicesSoap12 {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface clsDataAccessServicesSoap12Channel : Cuurency_Service.ServiceReference1.clsDataAccessServicesSoap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class clsDataAccessServicesSoap12Client : System.ServiceModel.ClientBase<Cuurency_Service.ServiceReference1.clsDataAccessServicesSoap12>, Cuurency_Service.ServiceReference1.clsDataAccessServicesSoap12 {
        
        public clsDataAccessServicesSoap12Client() {
        }
        
        public clsDataAccessServicesSoap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public clsDataAccessServicesSoap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clsDataAccessServicesSoap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clsDataAccessServicesSoap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
}
